# Generated by Django 5.1.7 on 2025-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_airport_latitude_remove_airport_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
