# Generated by Django 5.1.7 on 2025-03-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_airport_iata_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='country',
        ),
    ]
