# Generated by Django 5.1.7 on 2025-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_airline_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(max_length=10),
        ),
    ]
