# Generated by Django 5.1.7 on 2025-03-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_airline_iata_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='logitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
