# Generated by Django 5.1.7 on 2025-03-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_airport_latitude_airport_logitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
